version: 2
updates:
  # Enable version updates for npm
  - package-ecosystem: "npm"
    directory: "/src/memory"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "10:00"
    open-pull-requests-limit: 10
    labels:
      - "dependencies"
      - "npm"
    assignees:
      - "JamesPrial"
    commit-message:
      prefix: "chore"
      include: "scope"
    pull-request-branch-name:
      separator: "/"
    
  # Enable version updates for Docker
  - package-ecosystem: "docker"
    directory: "/src/memory"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "10:00"
    labels:
      - "dependencies"
      - "docker"
    commit-message:
      prefix: "chore"
      include: "scope"
    
  # Enable version updates for GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "10:00"
    labels:
      - "dependencies"
      - "github-actions"
    commit-message:
      prefix: "chore"
      include: "scope"