codecov:
  require_ci_to_pass: yes

coverage:
  precision: 2
  round: down
  range: "80...100"
  
  status:
    project:
      default:
        target: 85%
        threshold: 2%
        base: auto
        flags:
          - unittests
        paths:
          - "src"
          - "!src/memory"
        if_ci_failed: error
    patch:
      default:
        target: 80%
        threshold: 5%
        base: auto
        if_ci_failed: error

parsers:
  gcov:
    branch_detection:
      conditional: yes
      loop: yes
      method: no
      macro: no

comment:
  layout: "reach,diff,flags,tree"
  behavior: default
  require_changes: no
  require_base: no
  require_head: yes
  
ignore:
  - "test/**/*"
  - "**/*.test.ts"
  - "**/*.spec.ts"
  - "mcp-memory-fix/**/*"
  - "src/memory/**/*"
  - "dist/**/*"
  - "coverage/**/*"
  - "docs/**/*"

flags:
  unittests:
    paths:
      - src/
    carryforward: false