name: PR Source Branch Check

on:
  pull_request:
    branches:
      - main

jobs:
  check-source-branch:
    runs-on: ubuntu-latest
    name: Verify PR Source Branch
    steps:
      - name: Check PR source branch
        run: |
          echo "PR is from branch: ${{ github.head_ref }}"
          if [[ "${{ github.head_ref }}" != "release/v1.0.0" ]]; then
            echo "❌ PRs to main must come from release/v1.0.0 branch only"
            echo "Current PR is from: ${{ github.head_ref }}"
            exit 1
          fi
          echo "✅ PR is from the correct release branch (release/v1.0.0)"